#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=target --exclude=node_modules --languages=javascript,sql,c,ruby,go,c++,rust,python
mv .git/tags.$$ .git/tags
